export const UI_TREE = {
  fieldWrap:          "w-full space-y-2",
  label:              "block text-sm font-bold text-slate-800",
  requiredMark:       "ml-1 text-rose-500",
  helperText:         "text-xs font-medium text-slate-500",
  errorText:          "text-xs font-semibold text-rose-600",
  shell:              "rounded-3xl border border-slate-200 bg-white/95 p-3 shadow-sm",
  searchBox:          "mb-3 flex items-center gap-2 rounded-2xl border border-slate-200 bg-slate-50 px-3 py-2",
  searchInput:        "w-full bg-transparent text-sm font-medium text-slate-700 outline-none placeholder:text-slate-400",
  tree:               "max-h-80 space-y-1 overflow-y-auto pr-1",
  empty:              "rounded-2xl border border-dashed border-slate-200 bg-slate-50 px-4 py-6 text-center text-sm font-semibold text-slate-400",
  row:                "group flex w-full items-center gap-2 rounded-2xl px-2 py-2 text-left transition",
  rowDefault:         "text-slate-600 hover:bg-slate-100 hover:text-slate-900",
  rowSelected:        "bg-slate-900 text-white shadow-sm",
  toggle:             "flex h-7 w-7 shrink-0 items-center justify-center rounded-xl transition",
  toggleDefault:      "text-slate-400 group-hover:bg-white group-hover:text-slate-700",
  toggleSelected:     "bg-white/15 text-white",
  togglePlaceholder:  "h-7 w-7 shrink-0",
  icon:               "h-4 w-4 shrink-0",
  content:            "min-w-0 flex-1",
  title:              "truncate text-sm font-bold",
  subtitle:           "truncate text-xs font-medium opacity-70",
  levelBadge:         "shrink-0 rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-black uppercase tracking-wide text-slate-500",
  levelBadgeSelected: "bg-white/15 text-white",
  children:           "ml-4 border-l border-slate-200 pl-2",
  footer:             "mt-3 rounded-2xl bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-500",
  selectedValue:      "font-black text-slate-800",
};
